// Step 1: ABSUNIQUEID
SELECT ABSUNIQUEID 
FROM INTERNALDOCUMENT 
WHERE PROVISIONALCODE = 'DC2500000006';

//  Step 2 — ADSTORAGE
SELECT * 
FROM ADSTORAGE 
WHERE UNIQUEID = 67845120;

//   Step 3 — Max OUTWARDNO 
SELECT 
    COALESCE(MAX(CAST(VALUESTRING AS INTEGER)), 0) AS MAX_OUTWARDNO
FROM ADSTORAGE
WHERE NAMENAME = 'OUTWARDNO' AND FIELDNAME = 'OUTWARDNO';

// Step 4 — Check  OUTWARDDATE value
SELECT VALUEDATE 
FROM ADSTORAGE 
WHERE UNIQUEID = 67845265 AND NAMENAME = 'OUTWARDDATE' AND FIELDNAME = 'OUTWARDDATE';
        

// Step 5 — OUTWARDDATE and OUTWARDNO updating
UPDATE ADSTORAGE
SET VALUEDATE = CURRENT_DATE
WHERE UNIQUEID = 67845265 
AND NAMENAME = 'OUTWARDDATE' 
AND FIELDNAME = 'OUTWARDDATE'
AND VALUEDATE IS NULL;

// if value not null and you you want update then run 
UPDATE ADSTORAGE
SET VALUEDATE = CURRENT_DATE
WHERE UNIQUEID = 67845265 
AND NAMENAME = 'OUTWARDDATE' 
AND FIELDNAME = 'OUTWARDDATE';


// if not exits then creating 
INSERT INTO ADSTORAGE (
    UNIQUEID, 
    NAMEENTITYNAME,
    NAMENAME, 
    FIELDNAME, 
    KEYSEQUENCE, 
    SHARED, 
    DATATYPE, 
    VALUEINT, 
    VALUEBOOLEAN, 
    VALUELONG, 
    ABSUNIQUEID,
    VALUEDATE
) VALUES (
    67845265, 
    'InternalDocument',
    'OUTWARDDATE', 
    'OUTWARDDATE', 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    67845265,
    CURRENT_DATE
);




// CHECK OUTWARDNO row
SELECT *
FROM ADSTORAGE
WHERE UNIQUEID = 67845265 
AND NAMENAME = 'OUTWARDNO' 
AND FIELDNAME = 'OUTWARDNO';

//  INSERT OUTWARDNO + 1 
SELECT COALESCE(MAX(CAST(VALUESTRING AS INTEGER)), 100) AS MAX_OUTWARDNO
FROM ADSTORAGE
WHERE NAMENAME = 'OUTWARDNO'
AND FIELDNAME = 'OUTWARDNO'
AND VALUESTRING IS NOT NULL
AND REGEXP_LIKE(VALUESTRING, '^[0-9]+$');

//NEW_OUTWARDNO = MAX_OUTWARDNO + 1

// insert 
INSERT INTO ADSTORAGE (
    UNIQUEID, 
    NAMEENTITYNAME,
    NAMENAME, 
    FIELDNAME, 
    KEYSEQUENCE, 
    SHARED, 
    DATATYPE, 
    VALUESTRING, 
    VALUEINT, 
    VALUEBOOLEAN, 
    VALUELONG, 
    ABSUNIQUEID
) VALUES (
    67845265, 
    'InternalDocument',
    'OUTWARDNO', 
    'OUTWARDNO', 
    0, 
    0, 
    0, 
    '3007',  -- NEW_OUTWARDNO 
    0, 
    0, 
    0, 
    67845265
);



// Step 6 — Final check
SELECT * 
FROM ADSTORAGE 
WHERE UNIQUEID = 67845265;