// 
SELECT * 
FROM COMMERCIALINVOICE;

// Step 1: ABSUNIQUEID
SELECT ABSUNIQUEID 
FROM COMMERCIALINVOICE 
WHERE CODE = 'CD121220002';

//  Step 2 — ADSTORAGE
SELECT * 
FROM ADSTORAGE 
WHERE UNIQUEID = 49268665;

// Step 3 - if not exits then creating 
INSERT INTO ADSTORAGE (
    UNIQUEID, 
    NAMEENTITYNAME,
    NAMENAME, 
    FIELDNAME, 
    KEYSEQUENCE, 
    SHARED, 
    DATATYPE, 
    VALUEINT, 
    VALUEBOOLEAN, 
    VALUELONG, 
    ABSUNIQUEID,
    VALUEDATE
) VALUES (
    49268665, 
    'CommercialInvoice',
    'OutwardDate', 
    'OutwardDate', 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    49268665,
    CURRENT_DATE
);

//Step 4 final check
SELECT * 
FROM ADSTORAGE 
WHERE UNIQUEID = 49268665;


// For OUTWORD NO
SELECT *
FROM ADSTORAGE
WHERE UNIQUEID = 49268665 
AND NAMENAME = 'OUTWARDNO' 
AND FIELDNAME = 'OUTWARDNO';