# Generated by Django 4.2 on 2025-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DB2INST1.DATA',
            },
        ),
    ]
